#ifndef VOXBLOX_GSM_GLOBAL_FEATURE_MAP_FEATURE_LAYER_H_
#define VOXBLOX_GSM_GLOBAL_FEATURE_MAP_FEATURE_LAYER_H_

namespace voxblox {}  // namespace voxblox

#endif  // VOXBLOX_GSM_GLOBAL_FEATURE_MAP_FEATURE_LAYER_H_
